MiGestorEventos/MiGestorEventos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='gestor_eventos/login')), 
    path("admin/", admin.site.urls),
    path("gestor_eventos/", include("eventos.urls", namespace="eventosApp")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MiGestorEventos/eventos/urls.py
from django.urls import path
from .views import *

app_name = "eventos"

urlpatterns = [
    path("home", pagina_principal, name = "pagina_principal"),
    path("eventos/", lista_eventos.as_view(), name = "lista_Eventos"),
    path("eventos/crear", crear_eventos, name = "crear_Eventos"),
    path('eventos/editar/<int:pk>/', login_required(editar_evento.as_view(), login_url='/gestor_eventos/login/'), name = "editar_Eventos"),
    path('eventos/borrar/<int:pk>/', eliminar_evento.as_view(), name = "borrar_Eventos"),
    path("organizadores/", organizador_lista.as_view(), name = "lista_organizadores"),
    path("organizadores/crear", organizador_añadir.as_view(), name = "añadir_organizadores"),
    path('organizadores/editar/<int:pk>/', organizador_editar.as_view(), name = "editar_organizador"),
    path('organizadores/borrar/<int:pk>/', organizador_eliminar.as_view(), name = "borrar_organizador"),
    path("login/registro", pagina_registro, name = "pagina_registro"),
    path("login/", pagina_login, name = "pagina_login"),

]

MiGestorEventos/eventos/models.py
from django.db import models

#Modelo del Organizador
class organizador(models.Model):
    nombre_org = models.CharField(max_length=100)
    def __str__(self):
        return self.nombre_org

#Modelo del Evento
class evento(models.Model):
    nombre_event = models.CharField(max_length=100)
    fecha = models.DateField(auto_now_add=True)
    organizador_relacion = models.ForeignKey(organizador, on_delete = models.CASCADE)

MiGestorEventos/eventos/forms.py
from django import forms
from .models import evento
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

#Formulario para añadir eventos con palabra excluyente
class formularioEvento(forms.ModelForm):
    class Meta:
        model = evento
        fields = ['nombre_event','organizador_relacion']
        labels = {
        'nombre_event': 'Nombre del Evento',
        'organizador_relacion': 'Organizador del evento',
        }
    def clean_nombre_event(self):
        nombre = self.cleaned_data['nombre_event']
        if "Cancelado" in nombre:
            raise forms.ValidationError("El nombre del evento no puede contener la palabra 'Cancelado'.")
        return nombre

#Formulario para el inicio de sesión
class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

      
    
    

MiGestorEventos/eventos/views.py
from typing import Any
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.edit import FormView
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

#Vista de la página principal
def pagina_principal(request):
    return render(request, 'menu_principal.html')

#Vistas asociada al modelo de evento

class lista_eventos(ListView):
    model = evento
    template_name = 'lista_eventos.html'


def crear_eventos(request):
    if request.method == 'POST':
        form = formularioEvento(request.POST)
        if form.is_valid():
            form.save()
            return redirect('eventosApp:lista_Eventos')
    else:
        form = formularioEvento()
    return render(request, 'crear_evento.html', {'form': form})


class editar_evento(UpdateView):
    model = evento
    form_class = formularioEvento
    template_name = 'editar_eventos.html'
    success_url ="."

    def get_object(self):
        id = self.kwargs.get('pk')
        return evento.objects.get(id = id)
    
    def get_success_url(self):
        return reverse('eventosApp:lista_Eventos')
    

class eliminar_evento(DeleteView):
    model = evento
    template_name = 'eliminar_evento.html'
    success_url ="/gestor_eventos/eventos/"



#Vistas asociada al modelo de organizador


class organizador_lista(ListView):
    model = organizador
    template_name = 'lista_organizadores.html'


class organizador_añadir(CreateView):
    model = organizador
    fields = ['nombre_org']
    template_name = 'añadir_organizadores.html'
    success_url = '/gestor_eventos/organizadores/'



class organizador_editar(UpdateView):
    model = organizador
    fields = ['nombre_org']
    template_name = 'editar_organizador.html'
    success_url ="."

    def get_object(self):
        id = self.kwargs.get('pk')
        return organizador.objects.get(id = id)
    
    def get_success_url(self):
        return reverse('eventosApp:lista_organizadores')

class organizador_eliminar(DeleteView):
    model = organizador
    template_name = 'eliminar_organizador.html'
    success_url ="/gestor_eventos/organizadores/"

#Vistas asociada al modelo de inicio de sesión

def pagina_registro(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Cuenta fue creada por ' + user)
            return redirect('eventosApp:pagina_login')
    else:
        form = CreateUserForm()
    #Diseño de la página obtenido: https://jsfiddle.net/ivanov11/hzf0jxLg/
    return render(request, 'registro_login.html', {'form': form})

def pagina_login(request):
    context = {}

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username = username, password = password)
        if user is not None:
            login(request, user)
            return redirect('eventosApp:pagina_principal')
        else:
            messages.info(request, 'Usuario o contraseña incorrectas')
            return render(request, 'login.html', context)
    
    #Diseño de la página obtenido: https://jsfiddle.net/ivanov11/dghm5cu7/
    return render(request, 'login.html', context)

MiGestorEventos/eventos/templates/añadir_organizadores.html
<!doctype html>
<html lang="en">
  <head>
    {% block title %}
      <title>Eventos</title>
    {% endblock %}
    
    <style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		h3{
		text-align: center;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #000000;
			font-size:30px
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
		#div-content{
			width: 300px; 
			margin: 0 auto;
			margin-top: 100px;
		}
	</style>
  </head>
  <body>
    <!-- <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Añadir Organizador</button>
    </form>
    <a href="."><h2>Ver Organizadores</h2></a> -->

      <div class="container h-100" id="div-content" >
        <div class="d-flex justify-content-center h-100">
          <div class="user_card">
            <div class="d-flex justify-content-center">
              <h3 id="form-title">Añadir organizador</h3>
            </div>
            <div class="d-flex justify-content-center form_container">
              <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Añadir Organizador</button>
                </form>
                <a href="{% url 'eventosApp:lista_Eventos' %}"><h2>Ver Organizadores</h2></a>
            </div>
        </div>
      </div>
    </div>
  </body>
</html>

MiGestorEventos/eventos/templates/crear_evento.html
<!doctype html>
<html lang="en">
  <head>
    {% block title %}
      <title>Crear eventos</title>
    {% endblock %}

    <style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
    h3{
       text-align: center;
    }
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #000000;
			font-size:30px
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
		#div-content{
			width: 300px; 
			margin: 0 auto;
			margin-top: 100px;
		}
	</style>
  </head>
  <body>
        <div class="container h-100" id="div-content" >
          <div class="d-flex justify-content-center h-100">
            <div class="user_card">
              <div class="d-flex justify-content-center">
                <h3 id="form-title">Crear evento</h3>
              </div>
                <div class="d-flex justify-content-center form_container">
                    <form method="post">
                      {% csrf_token %}
                      {{ form.as_p }}
                      <button type="submit">Crear Evento</button>
                      <a href="{% url 'eventosApp:lista_Eventos' %}"><h2>Ver Eventos</h2></a>
                </div>
            </div>
          </div>
      </div>
</form>
  </body>
</html>

MiGestorEventos/eventos/templates/editar_eventos.html
<!doctype html>
<html lang="en">
  <head>
    {% block title %}
      <title>Crear eventos</title>
    {% endblock %}
  </head>
  <body>
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
        <a href=""><h2>Ver Eventos</h2></a>
</form>
  </body>
</html>

MiGestorEventos/eventos/templates/editar_organizador.html
<!doctype html>
<html lang="en">
  <head>
      <title>Editar Organizador</title>
    <style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
    h3{
       text-align: center;
    }
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #000000;
			font-size:30px
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
		#div-content{
			width: 300px; 
			margin: 0 auto;
		}
	</style>
  </head>
  <body>
        <div class="container h-100" id="div-content" >
          <div class="d-flex justify-content-center h-100">
            <div class="user_card">
              <div class="d-flex justify-content-center">
                <h3 id="form-title">Editar Organizador</h3>
              </div>
                <div class="d-flex justify-content-center form_container">
                    {% if 'ok' in request.GET %}
                      <p style="color: green">
                        Organizador editado correctamente
                      </p>
                    {% endif %}
                    <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Guardar</button>
                    <a href="{% url 'eventosApp:lista_organizadores' %}"><h2>Ver Organizadores</h2></a>
                    </form>
                </div>
            </div>
          </div>
      </div>
</form>
  </body>
</html>

MiGestorEventos/eventos/templates/eliminar_evento.html
<!doctype html>
<html lang="en">
  <head>
      <title>Eliminar eventos</title>
    <style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
    h3{
       text-align: center;
    }
    button{
      align-items: center;
    }
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #000000;
			font-size:30px
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
		#div-content{
			width: 300px; 
			margin: 0 auto;
			margin-top: 100px;
		}
	</style>
  </head>
  <body>
        <div class="container h-100" id="div-content" >
          <div class="d-flex justify-content-center h-100">
            <div class="user_card">
              <div class="d-flex justify-content-center">
                <h3 id="form-title">Crear evento</h3>
              </div>
                <div class="d-flex justify-content-center form_container">
                    <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <h3>¿Estás seguro de borrar el evento?</h3>
                    <button type="submit">
                        <a href="{% url 'eventosApp:lista_Eventos' %}"><h2>Si, borrar el evento</h2></a>
                    </button>
                    <a href="{% url 'eventosApp:lista_Eventos' %}"><h2>No, volver</h2></a>
                </div>
            </div>
          </div>
      </div>
</form>
  </body>
</html>

MiGestorEventos/eventos/templates/eliminar_organizador.html
<!doctype html>
<html lang="en">
  <head>
      <title>Eliminar eventos</title>
    <style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
    h3{
       text-align: center;
    }
    button{
      align-items: center;
    }
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #000000;
			font-size:30px
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
		#div-content{
			width: 300px; 
			margin: 0 auto;
			margin-top: 100px;
		}
	</style>
  </head>
  <body>
        <div class="container h-100" id="div-content" >
          <div class="d-flex justify-content-center h-100">
            <div class="user_card">
              <div class="d-flex justify-content-center">
                <h3 id="form-title">Crear evento</h3>
              </div>
                <div class="d-flex justify-content-center form_container">
                    <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <h3>¿Estás seguro de borrar el evento?</h3>
                    <button type="submit">
                        <a href="{% url 'eventosApp:lista_organizadores' %}"><h2>Si, borrar el organizador</h2></a>
                    </button>
                    <a href="{% url 'eventosApp:lista_organizadores' %}"><h2>No, volver</h2></a>
                </div>
            </div>
          </div>
      </div>
</form>
  </body>
</html>

MiGestorEventos/eventos/templates/lista_eventos.html
<!doctype html>
<html lang="en">
  <head>
    {% block title %}
      <title>Eventos</title>
    {% endblock %}
    <style>
            body{
                margin: 15px;
            }

            main{
                margin-left: 20px;
                margin-right: 20px;
            }
            h3{
                text-align: center;
            }
            span{
                color: rgb(243, 235, 81);
                text-decoration: none;
                padding: 15px;
                display: block;
                text-align: right;
                font-size: 20px;
            }
            .navbar ul{
                list-style-type: none;
                background-color: #437f74;
                padding: 0px;
                overflow: hidden;
            }

            .navbar a{
                color: white;
                text-decoration: none;
                padding: 15px;
                display: block;
                text-align: center;
            }

            .navbar a:hover{
                background-color: hsl(0, 0%, 10%);
            }

            .navbar li{
                float: left;
            }

        </style>
  </head>
  <body>
    <h3>Gestor de Eventos</h3>
        <nav class="navbar">
        <ul>
            <li><a href="{% url 'eventosApp:pagina_principal' %}">Home</a></li>
            <li><a href="{% url 'eventosApp:lista_organizadores' %}">Organizadores</a></li>
            <li><a href="{% url 'eventosApp:lista_Eventos' %}">Eventos</a></li>
            <span>{{request.user}}</span>
        </ul>
        </nav>
        
    <h1>Lista de eventos</h1>
    <ul>
        
        <a href="{% url 'eventosApp:crear_Eventos' %}"><h2>Crear Nuevo Evento</h2></a>

        <hr/> 

        {% for evento in object_list %}
            <li>{{ evento.nombre_event }} - {{ evento.fecha }} - {{ evento.organizador_relacion }} <a href="{% url 'eventosApp:editar_Eventos' evento.id%}">Editar</a> <a href="{% url 'eventosApp:borrar_Eventos' evento.id%}">Eliminar</a></li>
        {% endfor %}

        <hr/> 

        <!-- <a href="crear"><h2>Editar Eventos</h2></a> -->
        
    </ul>
  </body>
</html>

MiGestorEventos/eventos/templates/lista_organizadores.html
<!doctype html>
<html lang="en">
  <head>
    {% block title %}
      <title>Organizadores</title>
    {% endblock %}

    <style>
            body{
                margin: 15px;
            }

            main{
                margin-left: 20px;
                margin-right: 20px;
            }
            h3{
                text-align: center;
            }
            span{
                color: rgb(243, 235, 81);
                text-decoration: none;
                padding: 15px;
                display: block;
                text-align: right;
                font-size: 20px;
            }
            .navbar ul{
                list-style-type: none;
                background-color: #437f74;
                padding: 0px;
                overflow: hidden;
            }

            .navbar a{
                color: white;
                text-decoration: none;
                padding: 15px;
                display: block;
                text-align: center;
            }

            .navbar a:hover{
                background-color: hsl(0, 0%, 10%);
            }

            .navbar li{
                float: left;
            }

        </style>
  </head>
  <body>
    <h3>Gestor de Eventos</h3>
        <nav class="navbar">
        <ul>
            <li><a href="{% url 'eventosApp:pagina_principal' %}">Home</a></li>
            <li><a href="{% url 'eventosApp:lista_organizadores' %}">Organizadores</a></li>
            <li><a href="{% url 'eventosApp:lista_Eventos' %}">Eventos</a></li>
            <span>{{request.user}}</span>
        </ul>
        </nav>

    <ul> 
        <h2>Lista de Organizadores</h2>
        <a href="{% url 'eventosApp:añadir_organizadores' %}"><h2>Añadir Nuevo Organizador</h2></a>

        <hr/> 

        {% for organizador in object_list %} 
            <li> {{organizador.nombre_org}} <a href="{% url 'eventosApp:editar_organizador' organizador.id%}">Editar</a> <a href="{% url 'eventosApp:borrar_organizador' organizador.id%}">Eliminar</a> </li>
        {% endfor %}
    
        <hr/> 

    </ul>    
  </body>
</html>

MiGestorEventos/eventos/templates/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">Iniciar Sesión</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Usuario..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Contraseña..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Iniciar Sesión">
				   			</div>
					</form>

				</div>
		
                <div class="mt-4">
					<div class="d-flex justify-content-center links">
						¿No tienes una cuenta? <a href="{% url 'eventosApp:pagina_registro' %}" class="ml-2">Registrate</a>
					</div>
			</div>
		</div>
	</div>
</body>

</html>